return {
  background = "{{colors.background.default.hex}}",
  on_background = "{{colors.on_background.default.hex}}",
  surface = "{{colors.surface.default.hex}}",
  surface_container = "{{colors.surface_container.default.hex}}",
  on_surface = "{{colors.on_surface.default.hex}}",
  primary = "{{colors.primary.default.hex}}",
  primary_container = "{{colors.primary_container.default.hex}}",
  on_primary = "{{colors.on_primary.default.hex}}",
  secondary = "{{colors.secondary.default.hex}}",
  secondary_container = "{{colors.secondary_container.default.hex}}",
  tertiary = "{{colors.tertiary.default.hex}}",
  error = "{{colors.error.default.hex}}",
  outline = "{{colors.outline.default.hex}}",
}
