# Yazi dark flavor generated by Matugen.
# Foot keeps a dark terminal background, so this template intentionally uses
# Matugen's dark palette only.  The glyphs and file rules mirror myargonaut;
# only their semantic colors come from the wallpaper palette.

[mgr]
cwd = { fg = "{{colors.on_surface.default.hex}}", bold = true }
hovered = { bg = "{{colors.surface_container_high.default.hex}}" }
preview_hovered = { underline = true }
find_keyword = { fg = "{{colors.tertiary.default.hex}}", reversed = true }
find_position = { fg = "{{colors.on_surface_variant.default.hex}}", bold = true }
marker_copied = { fg = "{{colors.primary.default.hex}}", bg = "{{colors.primary.default.hex}}" }
marker_cut = { fg = "{{colors.error.default.hex}}", bg = "{{colors.error.default.hex}}" }
marker_marked = { fg = "{{colors.secondary.default.hex}}", bg = "{{colors.secondary.default.hex}}" }
marker_selected = { fg = "{{colors.tertiary.default.hex}}", bg = "{{colors.tertiary.default.hex}}" }
count_copied = { fg = "{{colors.on_primary.default.hex}}", bg = "{{colors.primary.default.hex}}", bold = true }
count_cut = { fg = "{{colors.on_error.default.hex}}", bg = "{{colors.error.default.hex}}", bold = true }
count_selected = { fg = "{{colors.on_tertiary.default.hex}}", bg = "{{colors.tertiary.default.hex}}", bold = true }
border_style = { fg = "{{colors.primary.default.hex}}" }

[status]
overall = { fg = "{{colors.primary.default.hex}}", bold = true }
sep_left = { open = "", close = "" }
sep_right = { open = "", close = "" }
progress_label = { bold = true }
progress_normal = { fg = "{{colors.primary.default.hex}}", bg = "{{colors.surface.default.hex}}" }
progress_error = { fg = "{{colors.error.default.hex}}", bg = "{{colors.surface.default.hex}}" }
perm_type = { fg = "{{colors.primary.default.hex}}" }
perm_read = { fg = "{{colors.secondary.default.hex}}" }
perm_write = { fg = "{{colors.tertiary.default.hex}}" }
perm_exec = { fg = "{{colors.error.default.hex}}" }
perm_sep = { fg = "{{colors.on_surface_variant.default.hex}}" }

[mode]
normal_main = { bg = "{{colors.primary.default.hex}}", fg = "{{colors.on_primary.default.hex}}", bold = true }
normal_alt = { bg = "{{colors.surface.default.hex}}", fg = "{{colors.primary.default.hex}}" }
select_main = { bg = "{{colors.tertiary.default.hex}}", fg = "{{colors.on_tertiary.default.hex}}", bold = true }
select_alt = { bg = "{{colors.surface.default.hex}}", fg = "{{colors.tertiary.default.hex}}" }
unset_main = { bg = "{{colors.outline.default.hex}}", fg = "{{colors.surface.default.hex}}", bold = true }
unset_alt = { bg = "{{colors.surface.default.hex}}", fg = "{{colors.on_surface_variant.default.hex}}" }

[input]
border = { fg = "{{colors.primary.default.hex}}" }
value = { fg = "{{colors.on_surface.default.hex}}" }
selected = { reversed = true }

[tabs]
active = { fg = "{{colors.on_primary.default.hex}}", bg = "{{colors.primary.default.hex}}", bold = true }
inactive = { fg = "{{colors.on_surface_variant.default.hex}}", bg = "{{colors.surface.default.hex}}" }

[cmp]
border = { fg = "{{colors.primary.default.hex}}", bg = "{{colors.surface_container_lowest.default.hex}}" }

[tasks]
border = { fg = "{{colors.primary.default.hex}}" }
hovered = { fg = "{{colors.secondary.default.hex}}", underline = true }

[which]
cols = 3
mask = { bg = "{{colors.surface_container_lowest.default.hex}}" }
cand = { fg = "{{colors.secondary.default.hex}}" }
rest = { fg = "{{colors.on_surface_variant.default.hex}}" }
desc = { fg = "{{colors.on_surface.default.hex}}", bold = true }
separator = "  "
separator_style = { fg = "{{colors.primary.default.hex}}" }

[help]
name = { fg = "{{colors.primary.default.hex}}", bold = true }
on = { fg = "{{colors.secondary.default.hex}}" }
run = { fg = "{{colors.tertiary.default.hex}}" }
desc = { fg = "{{colors.on_surface.default.hex}}" }
hover = { reversed = true }
footer = { fg = "{{colors.primary.default.hex}}", bold = true }

[spot]
border = { fg = "{{colors.primary.default.hex}}" }
cell = { fg = "{{colors.on_surface.default.hex}}" }

[filetype]
rules = [
  { mime = "image/*", fg = "{{colors.tertiary.default.hex}}" },
  { mime = "video/*", fg = "{{colors.tertiary_container.default.hex}}" },
  { mime = "audio/*", fg = "{{colors.tertiary_container.default.hex}}" },
  { mime = "application/zip", fg = "{{colors.secondary_container.default.hex}}" },
  { mime = "application/gzip", fg = "{{colors.secondary_container.default.hex}}" },
  { mime = "application/x-tar", fg = "{{colors.secondary_container.default.hex}}" },
  { mime = "application/x-7z*", fg = "{{colors.secondary_container.default.hex}}" },
  { mime = "application/x-rar*", fg = "{{colors.secondary_container.default.hex}}" },
  { mime = "application/pdf", fg = "{{colors.tertiary_container.default.hex}}" },
  { mime = "text/markdown", fg = "{{colors.primary.default.hex}}" },
  { mime = "text/html", fg = "{{colors.error.default.hex}}" },
  { url = "*.nix", fg = "{{colors.secondary.default.hex}}" },
  { url = "*.rs", fg = "{{colors.error.default.hex}}" },
  { url = "*.py", fg = "{{colors.tertiary.default.hex}}" },
  { url = "*.js", fg = "{{colors.tertiary.default.hex}}" },
  { url = "*.ts", fg = "{{colors.secondary.default.hex}}" },
  { url = "*.lua", fg = "{{colors.secondary.default.hex}}" },
  { url = "*.toml", fg = "{{colors.on_surface_variant.default.hex}}" },
  { url = "*.json", fg = "{{colors.tertiary.default.hex}}" },
  { url = "*.yaml", fg = "{{colors.error.default.hex}}" },
  { url = "*.yml", fg = "{{colors.error.default.hex}}" },
  { url = "flake.lock", fg = "{{colors.on_surface_variant.default.hex}}" },
  { url = "flake.nix", fg = "{{colors.secondary.default.hex}}" },
  { url = "*.conf", fg = "{{colors.on_surface_variant.default.hex}}" },
  { url = "Makefile", fg = "{{colors.primary.default.hex}}" },
  { url = "*.sh", fg = "{{colors.primary.default.hex}}" },
  { mime = "inode/x-empty", fg = "{{colors.on_surface_variant.default.hex}}" },
  { url = "*", is = "orphan", fg = "{{colors.error.default.hex}}" }
]

[icon]
prepend_dirs = [
  { name = "Desktop", text = "", fg = "{{colors.secondary.default.hex}}" },
  { name = "Documents", text = "󱔗", fg = "{{colors.secondary.default.hex}}" },
  { name = "Downloads", text = "", fg = "{{colors.secondary.default.hex}}" },
  { name = "Pictures", text = "", fg = "{{colors.secondary.default.hex}}" },
  { name = "Videos", text = "󰑈", fg = "{{colors.secondary.default.hex}}" },
  { name = "Music", text = "󰝚", fg = "{{colors.secondary.default.hex}}" },
  { name = "home", text = "", fg = "{{colors.secondary.default.hex}}" },
  { name = "Projects", text = "", fg = "{{colors.secondary.default.hex}}" },
  { name = "myNixOSConfig", text = "󱄅", fg = "{{colors.secondary.default.hex}}" },
  { name = ".git", text = "", fg = "{{colors.primary.default.hex}}" },
  { name = ".config", text = "", fg = "{{colors.secondary.default.hex}}" },
  { name = ".cache", text = "", fg = "{{colors.on_surface_variant.default.hex}}" },
  { name = ".local", text = "", fg = "{{colors.on_surface_variant.default.hex}}" },
  { name = "node_modules", text = "", fg = "{{colors.on_surface_variant.default.hex}}" }
]
prepend_exts = [
  { name = "nix", text = "󰋗", fg = "{{colors.secondary.default.hex}}" },
  { name = "lock", text = "󰋗", fg = "{{colors.on_surface_variant.default.hex}}" },
  { name = "rs", text = "", fg = "{{colors.error.default.hex}}" },
  { name = "py", text = "", fg = "{{colors.tertiary.default.hex}}" },
  { name = "js", text = "", fg = "{{colors.tertiary.default.hex}}" },
  { name = "ts", text = "", fg = "{{colors.secondary.default.hex}}" },
  { name = "lua", text = "", fg = "{{colors.secondary.default.hex}}" },
  { name = "json", text = "", fg = "{{colors.tertiary.default.hex}}" },
  { name = "yaml", text = "", fg = "{{colors.error.default.hex}}" },
  { name = "yml", text = "", fg = "{{colors.error.default.hex}}" },
  { name = "toml", text = "", fg = "{{colors.on_surface_variant.default.hex}}" },
  { name = "md", text = "󰉿", fg = "{{colors.primary.default.hex}}" },
  { name = "txt", text = "󰉿", fg = "{{colors.on_surface_variant.default.hex}}" },
  { name = "sh", text = "", fg = "{{colors.primary.default.hex}}" },
  { name = "bash", text = "", fg = "{{colors.primary.default.hex}}" },
  { name = "fish", text = "", fg = "{{colors.primary.default.hex}}" },
  { name = "conf", text = "", fg = "{{colors.on_surface_variant.default.hex}}" },
  { name = "css", text = "", fg = "{{colors.secondary.default.hex}}" },
  { name = "html", text = "", fg = "{{colors.error.default.hex}}" },
  { name = "svg", text = "󰜘", fg = "{{colors.tertiary.default.hex}}" },
  { name = "png", text = "󰉏", fg = "{{colors.tertiary.default.hex}}" },
  { name = "jpg", text = "󰉏", fg = "{{colors.tertiary.default.hex}}" },
  { name = "jpeg", text = "󰉏", fg = "{{colors.tertiary.default.hex}}" },
  { name = "gif", text = "󰉏", fg = "{{colors.tertiary.default.hex}}" },
  { name = "mp4", text = "", fg = "{{colors.tertiary_container.default.hex}}" },
  { name = "mkv", text = "", fg = "{{colors.tertiary_container.default.hex}}" },
  { name = "mp3", text = "", fg = "{{colors.tertiary_container.default.hex}}" },
  { name = "flac", text = "", fg = "{{colors.tertiary_container.default.hex}}" },
  { name = "wav", text = "", fg = "{{colors.tertiary_container.default.hex}}" },
  { name = "zip", text = "󰛫", fg = "{{colors.secondary_container.default.hex}}" },
  { name = "tar.gz", text = "󰛫", fg = "{{colors.secondary_container.default.hex}}" },
  { name = "tar.xz", text = "󰛫", fg = "{{colors.secondary_container.default.hex}}" },
  { name = "rar", text = "󰛫", fg = "{{colors.secondary_container.default.hex}}" },
  { name = "7z", text = "󰛫", fg = "{{colors.secondary_container.default.hex}}" },
  { name = "pdf", text = "", fg = "{{colors.tertiary_container.default.hex}}" },
  { name = "desktop", text = "", fg = "{{colors.secondary.default.hex}}" }
]
prepend_conds = [
  { if = "dir & hovered", text = "", fg = "{{colors.primary.default.hex}}" },
  { if = "dir", text = "", fg = "{{colors.secondary.default.hex}}" },
  { if = "exec", text = "", fg = "{{colors.primary.default.hex}}" },
  { if = "!dir & !exec", text = "", fg = "{{colors.on_surface_variant.default.hex}}" }
]
